# asciprec_for.py (help)
# !/usr/bin/env python3
# coding=utf-8
# young.daniel@epa.gov


"""
ROUTINE CONVERTS AN ASCII FILE TO A FORMATTED FILE CONTAINING DAILY VALUES.

EACH LINE OF OUTPUT CONSISTS OF THE YEAR, TEN DATA VALUES, AND THE LINE NUMBER.
PROGRAM SCANR
Rainfall
"""

