# syngen_for.py (help)
# !/usr/bin/env python3
# coding=utf-8
# young.daniel@epa.gov

"""
ROUTINE PREPARES CLIMATOLOGICAL INPUT FILES FROM THE SYNTHETIC CLIMATOLOGICAL DATA TAPE.

- TAPE1 CONTAINS THE SYNTHETIC RAIN PARAMETERS, ALPHA AND BETA.
- DATA4 CONTAINS THE SELECTED DAILY PRECIPITATION VALUES.
- DATA7 CONTAINS THE SELECTED AVERAGE DAILY TEMPERATURES.
- DATA11 CONTAINS THE NAME OF THE SELECTED CITY, THE EVAPORATIVE ZONE DEPTH, THE
  VEGETATION TYPE, MAX LAI, PLANTING AND HARVESTING DATES.
- DATA13 CONTAINS THE SELECTED SOLAR RADIATION VALUES.
"""

